// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rivdpexhpnlkrasuwult.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdmRwZXhocG5sa3Jhc3V3dWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1OTcyNDQsImV4cCI6MjA1NDE3MzI0NH0.77JgwjvXWftkj3GxfJV3z771QZTKnnk_X89xrvKrHTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);